version: "3"

services:
  influxdb:
    image: influxdb:2.6.1-alpine
    container_name: influxdb
    environment:
      - INFLUXDB_DB=influxdb
      - INFLUXDB_ADMIN_USER=influxdb
      - INFLUXDB_ADMIN_PASSWORD=influxdb
    volumes:
      - influxdb:/var/lib/influxdb2:rw
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
      - .data/grafana-provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin123
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - 3000:3000
    links:
      - influxdb

volumes:
  influxdb:
  grafana-storage: