version: "3"

services:
  # influxdb:
  #   image: arm64v8/influxdb:2.6.1-alpine
  #   expose:
  #     - "8086"
  #   environment:
  #     - INFLUXDB_DB=influxdb
  #     - INFLUXDB_ADMIN_USER=influxdb
  #     - INFLUXDB_ADMIN_PASSWORD=influxdb
  #   volumes:
  #     - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
      - .data/grafana-provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin123
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    # links:
    #   - influxdb

volumes:
  # influxdb:
  grafana-storage: